export enum RouteNames {
  CONTACT = "/contact",
  HOME = "/",
  LOGIN = "/login",
  NOT_FOUND = "*",
  PROJECTS = "/projects",
  PROJECTS_TICTACTOE = "/projects/tictactoe",
  PROJECTS_STATE = "/projects/state",
  PROJECTS_S3 = "/projects/s3",
  PROJECTS_ALIBABA = "/projects/alibaba",
  PROJECTS_PAYPAL = "/projects/paypal",
  PROJECTS_TEST = "/projects/test",
  PROJECTS_CAROUSEL = "/projects/carousel",
  SIGN_UP = "/signup",
};
